name: pull_request

on: pull_request

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate
      run: swift package generate-xcodeproj
    - name: Build
      run: xcodebuild build -sdk iphoneos -scheme 'BTImageView-Package'
    - name: Run tests
      run: xcodebuild test -destination 'name=iPhone 11' -scheme 'BTImageView-Package'
